"use client";

import ActionButton from "../ActionButton";

function DownloadRoadmapButton({ data, objective }) {
  const handleClick = async () => {
    const content = `# ${data.title}

**Objective:** ${objective}

## Executive Summary
${data.summary}

${(data.phases || [])
  .map(
    (p) => `
## ${p.phase}
**Goal:** ${p.goal}

**Tasks:**
${(p.tasks || []).map((t) => `- [ ] ${t}`).join("\n")}

**KPI:** ${p.kpi}
`
  )
  .join("\n")}

## Top Risks
${(data.risks || []).map((r) => `- ?? ${r}`).join("\n")}

## Quick Wins
${(data.quickWins || []).map((w) => `- ? ${w}`).join("\n")}

---
*Generated by FounderOS*`;

    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "execution-roadmap.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  return <ActionButton icon="??" label="Download Roadmap" doneLabel="Downloaded!" onClick={handleClick} />;
}

export default DownloadRoadmapButton;
