"use client";

import { useState } from "react";
import ActionButton from "../ActionButton";
import callOpenRouter from "../../../lib/openrouter";

function buildRoadmapMarkdown(data, objective) {
  return `# ${data.title}

**Objective:** ${objective}

## Executive Summary
${data.summary}

${(data.phases || [])
  .map(
    (p) => `
## ${p.phase}
**Goal:** ${p.goal}

**Tasks:**
${(p.tasks || []).map((t) => `- [ ] ${t}`).join("\n")}

**KPI:** ${p.kpi}
`
  )
  .join("\n")}

## Top Risks
${(data.risks || []).map((r) => `- ?? ${r}`).join("\n")}

## Quick Wins
${(data.quickWins || []).map((w) => `- ? ${w}`).join("\n")}

---
*Generated by FounderOS*`;
}

function ExportNotionModal({ markdown, onClose }) {
  const copyAll = async () => {
    await navigator.clipboard.writeText(markdown || "");
  };

  const downloadMarkdown = () => {
    const blob = new Blob([markdown || ""], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "notion-roadmap-export.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 1000,
        background: "rgba(0,0,0,0.95)",
        color: "#ffffff",
        overflowY: "auto",
        padding: "20px 16px",
      }}
    >
      <div style={{ maxWidth: 960, margin: "0 auto", display: "grid", gap: 14 }}>
        <div
          style={{
            position: "sticky",
            top: 0,
            zIndex: 5,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: 10,
            padding: "10px 12px",
            border: "1px solid rgba(255,255,255,0.15)",
            borderRadius: 12,
            background: "rgba(15,15,18,0.92)",
            backdropFilter: "blur(8px)",
            WebkitBackdropFilter: "blur(8px)",
          }}
        >
          <div style={{ fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif", fontWeight: 700, fontSize: "1.1rem" }}>
            Export to Notion
          </div>
          <button type="button" onClick={onClose} style={modalButtonStyle}>Close</button>
        </div>

        <div style={boxStyle}>
          <div style={boxTitleStyle}>Copy the markdown below</div>
          <textarea
            readOnly
            value={markdown || ""}
            style={{ width: "100%", minHeight: 220, background: "#0a0a0a", color: "#ffffff", border: "1px solid rgba(255,255,255,0.15)", borderRadius: 10, padding: 10, resize: "vertical" }}
          />
          <button type="button" onClick={copyAll} style={modalButtonStyle}>Copy All</button>
        </div>

        <div style={boxStyle}>
          <div style={boxTitleStyle}>Paste into Notion</div>
          <div style={{ opacity: 0.9 }}>Open Notion {"->"} New page {"->"} Type /markdown {"->"} Paste</div>
        </div>

        <div style={boxStyle}>
          <div style={boxTitleStyle}>Or use Notion API (advanced)</div>
          <pre style={{ margin: 0, whiteSpace: "pre-wrap", background: "#0a0a0a", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 10, padding: 10 }}>{`const { Client } = require('@notionhq/client')
// Paste your integration token below
const notion = new Client({ auth: 'YOUR_TOKEN' })
// Then run this script to auto-import`}</pre>
        </div>

        <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
          <button type="button" onClick={downloadMarkdown} style={modalButtonStyle}>Download .md</button>
          <button type="button" onClick={onClose} style={modalButtonStyle}>Close</button>
        </div>
      </div>
    </div>
  );
}

const boxStyle = {
  display: "grid",
  gap: 10,
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 12,
  background: "rgba(255,255,255,0.04)",
  padding: 12,
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
};

const boxTitleStyle = {
  fontWeight: 600,
};

const modalButtonStyle = {
  border: "1px solid rgba(255,255,255,0.2)",
  borderRadius: 999,
  background: "rgba(255,255,255,0.06)",
  color: "#ffffff",
  padding: "6px 12px",
  cursor: "pointer",
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  fontSize: "0.78rem",
};

function ExportNotionButton({ data, objective }) {
  const [show, setShow] = useState(false);
  void callOpenRouter;

  const handleClick = async () => {
    setShow(true);
  };

  const markdown = buildRoadmapMarkdown(data, objective);

  return (
    <>
      <ActionButton icon="??" label="Export to Notion" doneLabel="Ready!" onClick={handleClick} />
      {show && <ExportNotionModal markdown={markdown} onClose={() => setShow(false)} />}
    </>
  );
}

export default ExportNotionButton;
